config/routes.rb
Shwagr::Application.routes.draw do

  root :to => 'main#index'

  match "login", :to => "user_sessions#new", :as => "login"
  match "logout", :to => "user_sessions#destroy", :as => "logout"
  match '/message/inbox', :to => "message#inbox", :as => "inbox"

  resources :message

  resources :comments do
    resources :comments
    member do
      get :vote_up
      get :vote_down
    end
  end
  
  resources :categories do
    member do
      get :show_posts
    end
  end
  resources :posts do
    resources :comments
    collection do
     get :load_images
   end
   member do
     get :vote_up 
     get :vote_down
   end
  end
  resources :user_sessions
  resources :users do
    resources :posts do
      collection do
        get :view
      end
    end
  end

  
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
    # Ordered by most recent on default for now
    # store_location unless current_user
    #@posts = Post.find(:all, :order => "created_at DESC")
    @posts = (Post.all.sort {|a,b| b.shwagrithm <=> a.shwagrithm}).paginate(:page => params[:page], :per_page => 25)
  end
  
  
end

app/views/main/_post_view.html.haml
.grid_8.alpha.omega.post{:id => "post_#{post_view.id}"}
  .grid_1.alpha{:style => "text-align: center;"}
    - if current_user
      = link_to image_tag(current_user.votes.any? {|v| v.votable_id == post_view.id && v.value > 0} ? 'vote-up-selected.jpg' : 'vote-up.jpg'), vote_up_post_path(post_view), :class => 'vote'
      .vote_count{:style => "font-size: 14px; font-weight: bold;"}
        = post_view.vote_score
      = link_to image_tag(current_user.votes.any? {|v| v.votable_id == post_view.id && v.value < 0} ? 'vote-down-selected.jpg' : 'vote-down.jpg'), vote_down_post_path(post_view), :class => 'vote'
    - else
      = link_to image_tag('vote-up.jpg'), login_url
      .vote_count{:style => "font-size: 14px; font-weight: bold;"}
        = post_view.vote_score
      = link_to image_tag('vote-down.jpg'), login_url
  .grid_6
    .post_title
      - if post_view.is_link
        = link_to "#{post_view.name}", post_view.url
      - else
        = link_to "#{post_view.name}", post_path(post_view)
    - if post_view.is_link
      |
      (
      = link_to "#{post_view.is_a_sexy_link}", post_view.url
      )
    .clear
    - if post_view.video_link
      .grid_1.alpha{:style => "width: 20px;"}
        = link_to '', '#', :class => "play_movie"
    .grid_5
      Submitted
      = post_view.time_from_now
      ago by
      = link_to "#{post_view.user.username}", user_posts_path(post_view.user)
      to
      = link_to "#{post_view.category}", show_posts_category_path(Category.find_by_name(post_view.category)), :class => "category"
      %br/
      - if post_view.comments.count > 0
        = link_to "#{post_view.comments.size} Comments", post_path(post_view)
      - else
        = link_to 'Comment', post_path(post_view)
    .clear
    
    .grid_5.movie_container{:style => "display: none;"}
      - if post_view.is_a_sexy_link == "www.youtube.com"
        %object{ :width => "480", :height => "385"}
          %param{ :name => "movie", :value => "#{post_view.tube_url}&amp;hl=en_US"}
          %param{ :name => "allowFullScreen", :value => "true"}
          %param{ :name =>"allowscriptaccess", :value => "always"}
          %embed{ :src => "#{post_view.tube_url}", :type => "application/x-shockwave-flash", :allowscriptaccess => "always", :allowfullscreen => "true", :width => "480", :height => "385" }
      - elsif post_view.is_a_sexy_link == "vimeo.com"        
        %object{:width => "485px", :height => "385px", :type => "application/x-shockwave-flash", :id => "vimeo_clip_17406813", :name => "vimeo_clip_17406813", :data => "http://a.vimeocdn.com/flash/moogaloop/5.1.0/moogaloop.swf?v=1.0.8"}
          %param{:name => "bgcolor", :value => "#000000"}
          %param{:name => "allowscriptaccess", :value => "always"}
          %param{:name => "allowfullscreen", :value => "true"}
          %param{:name => "scalemode", :value => "noscale"}
          %param{:name => "quality", :value => "high"}
          %param{:name => "wmode", :value => "opaque"}
          %param{:name => "flashvars", :value => "server=vimeo.com&amp;player_server=player.vimeo.com&amp;cdn_server=a.vimeocdn.com&amp;embed_location=#{post_view.url}&amp;force_embed=0&amp;force_info=0&amp;moogaloop_type=moogaloop&amp;js_setupMoog=player17406812_1115591315.player.initiate&amp;js_onLoad=player17406812_1115591315.player.loaded&amp;clip_id=#{post_view.vimeo_url}&amp;fullscreen=1&amp;autoplay=0&amp;js_getConfig=player17406812_1115591315.getConfig"}

app/views/main/index.html.haml
.main_content.grid_8.alpha.omega{:style => "border: 1px; solid black;"}
  .grid_8.alpha.omega
    .grid_3
      .subtopic-holder
        %h1
          trending topics
    .grid_4{:style => "float: right; margin-top: 10px;"}
      = will_paginate @posts, {:outer_window => -1, :inner_window => 2}
  .clear
  = render :partial => 'post_view', :collection => @posts
  .grid_4.post{:style => "float: right; margin: 10px 5px 0 0;"}
    = will_paginate @posts, {:outer_window => -1, :inner_window => 2}
  %br/
.bottom_leaf