config/routes.rb
Shwagr::Application.routes.draw do

  root :to => 'main#index'

  match "login", :to => "user_sessions#new", :as => "login"
  match "logout", :to => "user_sessions#destroy", :as => "logout"
  match '/message/inbox', :to => "message#inbox", :as => "inbox"

  resources :message

  resources :comments do
    resources :comments
    member do
      get :vote_up
      get :vote_down
    end
  end
  
  resources :categories do
    member do
      get :show_posts
    end
  end
  resources :posts do
    resources :comments
    collection do
     get :load_images
   end
   member do
     get :vote_up 
     get :vote_down
   end
  end
  resources :user_sessions
  resources :users do
    resources :posts do
      collection do
        get :view
      end
    end
  end

  
end

app/models/post.rb
class Post < ActiveRecord::Base

  #before_save                   :parse_text
                                                                           
  belongs_to                    :user, :touch => true                            
                                                                           
  validates_presence_of         :category, :name                                 
  validates_presence_of         :url, :unless => Proc.new {|post| post.text}     
                                                                           
  before_save                   :prepare_posts                                   
  validate                      :category?                                       
                                                                           
                                                                           
  has_many                      :votes, :as => :votable                          
  has_many                      :voting_users,                                   
                                :through => :votes,                              
                                :source => :user
                                                                           
  has_many                      :comments, :as => :commentable                                        
  accepts_nested_attributes_for :comments, :allow_destroy => true
  
  has_friendly_id               :name, :use_slug => true
                    
  def time_from_now
    days_past = (Time.now - self.created_at.to_time)/1.day
    hours_past = (Time.now - self.created_at.to_time)/1.hour
    minutes_past = (Time.now - self.created_at.to_time)/1.minute
    seconds_past = (Time.now - self.created_at.to_time)/1.second
    if hours_past > 23
      time = Fixnum.induced_from(days_past)
      time_description = days_past > 1 ? "days" : "day"
    elsif hours_past > 1 && hours_past < 24
      time = Fixnum.induced_from(hours_past)
      time_description = hours_past > 1 ? "hours" : "hour"
    elsif hours_past < 1 && seconds_past > 60
      time = Fixnum.induced_from(minutes_past)
      time_description = minutes_past > 1 ? "minutes" : "minute"
    else
      time = Fixnum.induced_from(seconds_past)
      time_description = seconds_past > 1 ? "seconds" : "second"
    end
    return time.to_s + " " + time_description.to_s
  end
  
  def is_a_sexy_link
    @uri = URI.parse(self.url)
    return @uri.host
  end
  
  def video_link
    case self.is_a_sexy_link
    when "www.youtube.com", "vimeo.com"
      return true
    end
  end
  
  def imgur_url
    case self.is_a_sexy_link
    when "i.imgur.com"
      return true
    end
  end
  
  def tube_url
    link = self.url.gsub(/watch\?v=/, 'v/')
    link + "?fs=1"
  end
  
  def vimeo_url
    link = self.url.split(/http:\/\/vimeo.com\//)[1]
  end
  
  def category?
    if self.category
      unless Category.exists?(:name => self.category.downcase)
        errors.add(:category, "There's no categories with that name.")
      end
      return true
    end
  end
  
  def prepare_posts
    if self.category
      self.update_attribute("category", self.category.downcase) unless self.category == self.category.downcase
      if self.url?
        self.url = "http://" + self.url unless self.url.match /^(https?|ftp):\/\//
      end
    end
  end
  
  def vote_score
    self.votes.inject(0){|sum, vote| sum + vote.value}
  end
  
  def shwagrithm
    a = self.created_at
    b = Time.parse("October 4 1984 3:54am")
    ts = a - b
    if self.vote_score > 0
      y = 1
    elsif self.vote_score < 0
      y = -1
    else
      y = 0
    end
    z = self.vote_score.abs
    if z < 1
      z = 1
    end
    rating = 45000 * Math.log10(z) + y * ts
  end
  
  #imgur cookie = lodhrt2tttmia6qkh93ntei4q1

  def imgur(key, cookie, file_path)
    data = {
      :key => key, :image => File.open(file_path)
    }
    headers = {
      "Cookie" => "IMGURSESSION=#{cookie}"
    }

    http      = Net::HTTP.new("imgur.com")
    path      = "/api/upload.json"
    response  = http.post(path, data, headers)
    json      = JSON.parse(response.body)["rsp"]["image"] rescue nil
  end
  

  private
  
  def parse_text
    if self.is_link != true
      self.text = RedCloth.new(text).to_html
    end
  end
  
end

app/controllers/posts_controller.rb
require 'uri'

class PostsController < ApplicationController
  
  before_filter :require_user, :only => [:edit]
  
  def index
    @posts = User.find(params[:user_id]).posts.sort{|x,y| y.created_at <=> x.created_at }.paginate(:page => params[:page], :per_page => 25)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end

  def show
    @post = Post.find(params[:id])

    @commentable = find_commentable
    @comments = @commentable.comments

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  def new
    @post = Post.new
    @cat_names = Category.all.collect {|c| c.name }.inspect
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end


  def edit
    @post = Post.find(params[:id])
  end

  #TO DO , fix this bullshit. This shold be a virgin posts controller for create.
  def create
    @post = current_user.posts.create(params[:post])
    if @post.save
      @vote = Vote.create(:user_id => current_user.id, :value => 1)
      @post.votes << @vote
      
      flash[:notice] = "Successfully created comment."
      redirect_to post_path(@post)
    else
      render :action => 'new'
    end
  end


  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(user_posts_path(current_user), :notice => "Post was deleted.") }
      format.xml  { head :ok }
    end
  end  
  
  def vote_up
    get_vote
    @vote.value += 1 unless @vote.value == 1
    @vote.save
    respond_to do |format|
      format.js { render :action => "vote", :layout => false }
    end
  end
  
  def vote_down
    get_vote
    @vote.value -= 1 unless @vote.value == -1
    @vote.save
    respond_to do |format|
      format.js { render :action => "vote", :layout => false }
    end
  end
  
  def load_images
    @url = params[:url]
    @url_root = (URI.parse(@url)).host
    @images = rape_that_sites(@url)
  end
  
  private
  
    def rape_that_sites(url)
      rapi = Scraper.define do
        array :images
        process "img", :images => "@src"
        result :images
      end
      uri = URI.parse(url)
      return rapi.scrape(uri)
    end

  def find_commentable
    params.each do |name, value|
      if params[:controller] == "comments"
        return Comment.find(params[:comment][:id])
      elsif params[:controller] == "posts" 
        return Post.find(params[:id])
      end
    end
    nil
  end

  def get_vote
    current_post = Post.find(params[:id])
    @post = current_post
    @vote =  current_post.votes.find_by_user_id(current_user.id)
    unless @vote
      @vote = Vote.create(:user_id => current_user.id, :value => 0)
      current_post.votes << @vote
    end
  end
  
  def require_user
    debugger
    unless current_user == Post.find(params[:id]).user
      store_location
      flash[:notice] = "You must be logged in to access this page"
      redirect_to login_url
      return false
    end
  end
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment.html.haml
.grid_7.post.alpha.omega{:id => "comment_#{comment.id}"}

  .grid_1.alpha{:style => "text-align: center;"}
    - if current_user
      = link_to image_tag(current_user.votes.any? {|v| v.votable_id == comment.id && v.value > 0} ? 'vote-up-selected.jpg' : 'vote-up.jpg'), vote_up_comment_path(comment), :class => 'vote'
      .vote_count{:style => "font-size: 14px; font-weight: bold;"}
        = comment.vote_score
      = link_to image_tag(current_user.votes.any? {|v| v.votable_id == comment.id && v.value < 0} ? 'vote-down-selected.jpg' : 'vote-down.jpg'), vote_down_comment_path(comment), :class => 'vote'
    - else
      = link_to image_tag('vote-up.jpg'), login_url
      .vote_count{:style => "font-size: 14px; font-weight: bold;"}
        = comment.vote_score
      = link_to image_tag('vote-down.jpg'), login_url
  .grid_5
    - if params[:controller] == "message"
      %i
        = link_to Post.find(comment.post_parent_id).name ,post_url(comment.post_parent_id)
      %br/
    %b{:style => "color: #9B4545;"}
      =h comment.user.username if comment.user 
    = "( " + comment.time_from_now + " ago )"
    %br/
    =h raw RedCloth.new(comment.text).to_html
    = link_to 'Reply', '#', :class => "comment"
    %br/
    .comment_form
      - form_for [comment, Comment.new] do |f|
        = f.hidden_field :id, :value => comment.id
        = f.label 'Comment'
        %br/
        = f.text_area :text, :style => "height: 100px; width: 400px;"
        %br/
        = f.submit 'Submit', :class => 'button'
  .clear
  .grid_5
    - if comment.comments
      = render :partial => 'posts/comment', :collection => comment.comments
.clear

app/views/posts/_form.html.haml
- form_for @post do |f|
  -if @post.errors.any?
    #errorExplanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg
  :javascript
    $(document).ready(function() {
    $("input#post_category").autocomplete({
    
    source: #{@cat_names}
    
    });
    });
  .post_nav
    .i
      = link_to 'Link ', '#', :class => 'text_link_toggle' 
    .i
      \&nbsp;or&nbsp;
    .i
      = link_to ' Rant', '#', :class => 'text_link_toggle'
  %br/
  .field_container.grid_6.alpha
    .field{:style => "visibility: hidden;"}
      = f.check_box :is_link, :checked => true
    .field
      = f.label :name, 'Title'
      %br/
      = f.text_field :name
    .field.text_link
      = f.label :url, 'Website Link'
      %br/
      = f.text_field :url
      -#
        .field
          = f.label :thumb_preview, 'Choose a Preview Image'
          %br/
          #load_images
        .clear
    
    .field.text_link{:style => "display: none;"}
      = f.label :text
      %br/
      = f.text_area :text
    .field
      = f.label :category, 'Choose A Topic'
      %br/
      .grid_4.alpha
        - for category in Category.all
          .category-choice
            = f.radio_button(:category, "#{category.name}", :style => "display: none;")
            = f.label "category_" + category.name, "#{category.name}"
    .clear
    %br/
    
    .actions
      = f.submit 'save', :class => 'button'
      
.clear

app/views/posts/_load_images.html.haml
- @images[0..2].each do |img|
  .grid_1
    = image_tag("http://" + @url_root + img, :height => 50)

app/views/posts/_post.haml
.grid_8.alpha.omega.post{:id => "post_#{post.id}"}
  .grid_1.alpha{:style => "text-align: center;"}
    - if current_user
      = link_to image_tag(current_user.votes.any? {|v| v.votable_id == post.id && v.value > 0} ? 'vote-up-selected.jpg' : 'vote-up.jpg'), vote_up_post_path(post), :class => 'vote'
      .vote_count{:style => "font-size: 14px; font-weight: bold;"}
        = post.vote_score
      = link_to image_tag(current_user.votes.any? {|v| v.votable_id == post.id && v.value < 0} ? 'vote-down-selected.jpg' : 'vote-down.jpg'), vote_down_post_path(post), :class => 'vote'
    - else
      = link_to image_tag('vote-up.jpg'), login_url
      .vote_count{:style => "font-size: 14px; font-weight: bold;"}
        = post.vote_score
      = link_to image_tag('vote-down.jpg'), login_url    
  .grid_6
    .post_title
      - if post.is_link
        = link_to "#{post.name}", post.url
      - else
        = link_to "#{post.name}", post_path(post)
    - if post.is_link
      |
      (
      = link_to "#{post.is_a_sexy_link}", post.url
      )
    .clear
    Submitted
    = post.time_from_now
    ago by
    = link_to "#{post.user.username}", user_posts_path(post.user)
    to
    = link_to "#{post.category}", ''
    %br/
    - if post.comments.count > 0
      = link_to "#{post.comments.size} Comments", post_path(post)
    - else
      = link_to 'Comment', post_path(post)
    - if current_user == User.find(params[:user_id])
      = link_to 'Edit', edit_post_path(post)
      = link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete

app/views/posts/edit.html.haml
.subtopic-holder
  %h1 Editing post
.grid_8.main_content{:style => "min-height: 620px;"}
  .grid_7
    = render 'form'
.bottom_leaf

app/views/posts/index.html.haml
.grid_3
  .subtopic-holder
    %h1
      = User.find(params[:user_id]).username + "'s posts"
.grid_4{:style => "float: right; margin-top: 10px;"}
  = will_paginate @posts, {:outer_window => -1, :inner_window => 2}
.clear
.grid_8.main_content
  = render :partial => 'post', :collection => @posts
  .grid_4.post{:style => "float: right; margin: 10px 5px 0 0;"}
    = will_paginate @posts, {:outer_window => -1, :inner_window => 2}
.bottom_leaf

app/views/posts/load_images.js.haml
== $("#load_images").html("#{ escape_javascript(render :partial => 'posts/load_images') }");

app/views/posts/new.html.haml
.grid_8.main_content{:style => "min-height: 618px;"}
  = render 'form'
.bottom_leaf

app/views/posts/show.html.haml
.grid_8.omega.main_content{:style => "min-height: 620px;"}
  .grid_1.alpha{:style => "text-align: center;"}
    - if current_user
      = link_to image_tag(current_user.votes.any? {|v| v.votable_id == @post.id && v.value > 0} ? 'vote-up-selected.jpg' : 'vote-up.jpg'), vote_up_post_path(@post), :class => 'vote'
      .vote_count{:style => "font-size: 14px; font-weight: bold;"}
        = @post.vote_score
      = link_to image_tag(current_user.votes.any? {|v| v.votable_id == @post.id && v.value < 0} ? 'vote-down-selected.jpg' : 'vote-down.jpg'), vote_down_post_path(@post), :class => 'vote'
    - else
      = link_to image_tag('vote-up.jpg'), login_url
      .vote_count{:style => "font-size: 14px; font-weight: bold;"}
        = @post.vote_score
      = link_to image_tag('vote-down.jpg'), login_url
  .grid_6

    - if @post.is_link
      .headline
        =h link_to @post.name, @post.url
      - if @post.is_a_sexy_link == "www.youtube.com"
        .grid_1.alpha{:style => "width: 20px;"}
          = link_to '', '#', :class => "play_movie"
      .grid_5
        %p
          Posted by
          = link_to User.find(@post.user.id).username, user_posts_path(@post.user)
          to
          =h link_to @post.category, show_posts_category_path(Category.find_by_name(@post.category)), :class => "category"
          (
          = @post.time_from_now + " ago"
          )
        - if @post.imgur_url
          .clear
          = link_to image_tag(@post.url, :width => "500"), @post.url
    
    - else
      .headline
        =h @post.name
      .grid_5
        =h "#{'Posted by ' + User.find(@post.user.id).username + ' to '}"
        =h link_to @post.category, show_posts_category_path(Category.find_by_name(@post.category)), :class => "category"
        (
        = @post.time_from_now + " ago"
        )
      %br/
      %p
        =h raw RedCloth.new(@post.text).to_html
    
    .grid_5.movie_container{:style => "display: none;"}
      %object{ :width => "480", :height => "385"}
        %param{ :name => "movie", :value => "#{@post.tube_url}&amp;hl=en_US"}
        %param{ :name => "allowFullScreen", :value => "true"}
        %param{ :name =>"allowscriptaccess", :value => "always"}
        %embed{ :src => "#{@post.tube_url}", :type => "application/x-shockwave-flash", :allowscriptaccess => "always", :allowfullscreen => "true", :width => "480", :height => "385" }
  
  .grid_7
    - form_for [@commentable, Comment.new] do |f|
      =h f.label :text, 'Got something to say?'
      %br/
      =h f.text_area :text, :style => "height: 100px;"
      %br/
      = f.submit "Submit", :class => 'button'
    .clear
    %br/
    - if @post.comments.count > 0
      %p
        What other people think :
  .clear
  .grid_7
    = render :partial => 'comment', :collection => @comments
.bottom_leaf

=# TODO : Make these options applicable only for the current_user == post.users
=# link_to 'Edit', edit_post_path(@post)
=# link_to 'Delete', post_path(@post), :method => :delete

app/views/posts/vote.js.haml
==  $("#post_#{@post.id}").replaceWith("#{ escape_javascript(render :partial => 'main/post_view', :locals => {:post_view => @post}) }");