config/routes.rb
Shwagr::Application.routes.draw do

  root :to => 'main#index'

  match "login", :to => "user_sessions#new", :as => "login"
  match "logout", :to => "user_sessions#destroy", :as => "logout"
  match '/message/inbox', :to => "message#inbox", :as => "inbox"

  resources :message

  resources :comments do
    resources :comments
    member do
      get :vote_up
      get :vote_down
    end
  end
  
  resources :categories do
    member do
      get :show_posts
    end
  end
  resources :posts do
    resources :comments
    collection do
     get :load_images
   end
   member do
     get :vote_up 
     get :vote_down
   end
  end
  resources :user_sessions
  resources :users do
    resources :posts do
      collection do
        get :view
      end
    end
  end

  
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Shwagr.com || Demand The Impossible
    = stylesheet_link_tag :all
    %link{ :rel => "shortcut icon", :href => "/favicon.png", :type => "image/x-icon"}
    = javascript_include_tag 'http://www.google.com/jsapi'
    = javascript_include_tag 'jquery-1.4.2.min', 'application', 'chroma-hash'
    :plain
      <script type="text/javascript" charset="utf-8">
         google.load("jqueryui", "1.8");
      </script>    
    = csrf_meta_tag
  %body
    .header
      .system_messages
        - flash.each do |name,msg|
          = content_tag :div, msg, :id => "flash_#{name}", :style => "color: #fff; text-align: center;"
    .main_bg
      .container_12
        .clear
        .grid_12.alpha.omega
          .grid_8.alpha.omega
            = link_to '', root_path, :style => "margin: 20px 0; height: 100px; width: 460px; display: block;"
          .grid_4
            #user_nav
              - if current_user
                = link_to image_tag(current_user.new_responses.blank? ? 'mailgray.png' : 'mail.jpg'), inbox_url
                = link_to "#{current_user.username}", user_posts_path(current_user)
                = link_to  "Edit Profile", edit_user_path(:current)
                = link_to "Logout", logout_path
              - else
                = link_to "Register", new_user_path
                = link_to "Login", login_path
            .clear
            .grid_2.submit
              - if current_user
                = link_to "Submit Stuff", new_user_post_path(current_user.id) 
              - else
                = link_to "Submit Stuff", login_path
        .clear
        .grid_8
          = yield
        .grid_4.omega.sideNav
          - if current_user == nil
            :javascript
              $(document).ready(function() {
                $(".cats").hide();
                $(".advert").click(function(){
                  $(".advert").hide();
                  $(".cats").slideDown();
                });
                $(".advert").delay(10000000).slideUp(function(){
                  $(".cats").slideDown();
                });
              });
            .advert
              .grid_2.arrow_block{:style => "margin-top: 5px;"}
                = image_tag('up-arrow.jpg')
              .clear
              %ul
                %li
                  %span
                    1.
                  Register Anonymously
                %li
                  %span
                    2.
                  Share Your Shwag
                %li
                  %span
                    3.
                  Commit Actions
              .grid_2.arrow_block
                = image_tag('down-arrow.jpg')
          .grid_4.alpha.omega.cats
            - for category in @categories
              %li
                .new_posts
                  - if current_user && !current_user.last_logins.select{|ll|ll.category_id == category.id}.empty? && Post.find(:all, :conditions => ["created_at > ? AND category = ? AND user_id != ?", current_user.last_logins.find_by_category_id(category).updated_at, category.name, current_user]).size > 0
                    .number
                      = Post.find(:all, :conditions => ["created_at > ? AND category = ? AND user_id != ?", current_user.last_logins.find_by_category_id(category).updated_at, category.name, current_user]).size
                  - else
                    \&nbsp;
                .link
                  = link_to "#{category.name}", show_posts_category_path(category)
          .clear
          .red_box_of_love
            = link_to image_tag('action-4.jpg', :style => 'border: none;'), "http://shwagr.com/posts/modern-anarchist-societies-series-abahlali-basemjondolo-the-autonomous-exemplars-of-south-africa"
          .clear
      
        .clear
      .clear
      .footer
        .footer_body
          .text
            Shwagr : [sh·wa·gr] n. an anarcho-aggregator of content related to self-reliability, non-violence, and art. 
      
:javascript
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-19995267-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();